### PR TITLE
Introduce ConsoleCommand.RunAsync - the asynchronous equivalent of ConsoleCommand.Run

### PR DESCRIPTION
**Pull request by MarkKharitonov**

### CODE REVIEW

**Comment by fschwiet** [comment]
Hi Mark.  My initial impression for this is that there isn't a real use case for this- letting things run async we might free up a thread for some people do something else with, but that seems pretty negligible.

**Comment by MarkKharitonov** [comment]
The reason for this PR is a desire to consume 3rd party async APIs while using ManyConsole. There are APIs out there that do not have a blocking alternative. Without ManyConsole a person can just declare async Main entry point and consume the APIs without ever blocking.

I think it makes sense to give the same experience with ManyConsole.

**Comment by lejsekt** [comment]
Hi,
this is definitely interesting as right now we have to wrap the console command with our own async console command wrapper to be able to reasonably use e.g. http client within the command.
Please merge this

**Comment by fschwiet** [comment]
My concern with the approach taken in the PR is that people have to use all async commands or all non-async commands, and depending on that change their implementation of Main.  The typical Main implementation calling into ManyConsole is something the developer could previously copy'n'paste and forget about forever.  With the approach in this PR that is lost.

> we have to wrap the console command with our own async console command wrapper

I don't see what the issue is with blocking in ConsoleCommand.Run() implementation.  One could create a reusable class derived of ConsoleCommand to take care of that (sealing Run() which calls into a new RunAsync()) and that could be worth including in the release (maybe given a name like ConsoleCommandAsync so its easily found by autocomplete?).

Sorry.  If you have other ideas for changes please feel free to create an issue first and we can talk about potential problems before the work is done.

**Pull request closed without merging**
