### PR TITLE
.NET Standard 2.0 Support

### LINKED ISSUE #34: Support for .NET standard
Any plan on plan on supporting `.NET standard`?

Even `1.6` would be enough.

### PR DESCRIPTION
**Pull request by hjsanchez**
Hi Guys,

I've been using for a while this project through Nuget but now I need to have the same functionality in a Linux environment so I thought it would be a good idea to port this project to Net Standard. 

Reviewing the code I only saw we needed to change the P/Invoke code and the logic to parse Input Parameters

Hopefully this resolves #34

### CODE REVIEW

**Comment by pinkfloydx33** [comment]
My concern is that `CommandLineToArgvW` is a bit more complex then this so the behavior could end up different for classic framework vs netstandard when both run on windows. It's probably better to still use interop but switch on the platform/runtime information. I've seen the source for `CommandLineToArgvW` (I think I may have linked to it in this project before), it may also be better to reimplement it directly

**Comment by fschwiet** [comment]
Sorry I haven't really been active with ManyConsole so this PR is falling behind.

What I imagine to getting to .NET standard 2.0 support:

- update the tests to use vanilla NUnit (or xUnit).  They're written in NJasmine which is a test framework I wrote but it is even less supported now than Manyconsole.
- Split the ConsoleModeCommand into a separate optional DLL (moving CommandLineParser into. that) and leaving its .NET version as is (deferring support for CommandLineParser with .NetStandard 2.0... I don't know if its really used much).  I think it could be packaged into the same Nuget class such that its only deployed for assemblies that support its version of .NET
- build/test/package scripts should be updated so they build, run and package the nuget assembly
  - the package step is overly complicated since it runs nuget spec and using for-xml to update the spec file, I should have just kept the spec file in source control (though I think we'll still need for-xml to update the version info, maybe we can stick in some release notes).  The version info goes into th nuget spec and the assembly info, maybe there is an easier way to do that and keep them in sync.
  

The later would be a breaking change so we'd update the major version.  The build/test/package scripts should be updated to keep working and I'm not particularly excited to do that myself either.  I can help though answering questions.  Once these criteria are met and I can see things work in my own projects using ManyConsole then I'd be comfortable putting the update and nuget and would be willing to hand off project ownership if desired.

Thanks for the interest, getting these updates through just hasn't been a priority for me but I'll do what I can to not be in the way if you two want to do the work.

**Comment by chrisg32** [comment]
I would be willing to help rewrite test cases or wherever else needs work. XUnit with fluent assertions is my personal preference but I am also good with vanilla XUnit or NUnit.

If you were to drop 4.0 support, you could leave interop behind. I know this leave some projects stuck on the current nuget package but it would definitely simplify things. As @pinkfloydx33 mentioned, then using a direct re-implementation of `CommandLineToArgvW` would allow for a single code path for all supported platforms.

**Comment by pinkfloydx33** [comment]
https://github.com/fschwiet/ManyConsole/issues/34#issuecomment-341359317

My original comment with link to the algorithm and an implementation (in C)

**Comment by fschwiet** [comment]
> If you were to drop 4.0 support, you could leave interop behind.

I was thinking break the code that needs interop into a separate dependency that would stay at the older version of .NET so its not a breaking change for existing users.  Updating it so it works on .NET Standard 2.0 could happen later if someone is motivated to make it happen.

It the same time, the tests for that project might need to be split off as well.  Not sure.

**Comment by fschwiet** [comment]
> I would be willing to help rewrite test cases or wherever else needs work. XUnit with fluent assertions is my personal preference but I am also good with vanilla XUnit or NUnit.

I would just go for vanilla NUnit for know with the existing version of NUnit.  This way the ConsoleModeCommand DLL that would be split off can keep referencing using it.  The rest of the tests could be moved forward to a newer NUnit or XUnit as the main DLL is updated to .netstandard 2.0.  For me NUnit/xUnit are fairly interchangeable if you avoid the fancy features.

**Comment by fschwiet** [comment]
Closed as  the intent was achieved by PR #49, thanks everyone.

**Pull request closed without merging**
