### PR TITLE
Net standard

### PR DESCRIPTION
**Pull request by Roadrunner67**
I believe I have addressed the intentions behind your comments on  #47.
There is one nupkg produced, which targets both netstandard2.0 and net46.
Only the latter contains ConsoleModeCommand.
Everything builds, tests, and packs from the build script.

### CODE REVIEW

**Comment by Roadrunner67** [comment]
Bump!

**Comment by fschwiet** [comment]
I reviewed the changes and they looked good, but didn't have time last weekend to smoke test.

**Comment by Roadrunner67** [comment]
I seem to have an unicode issue with _Generate-Assembly-Info_ and the copyright symbol.
Do you manually edit the resulting AssemblyInfo's to get rid of the superfluous Â before ©?

**Comment by hjsanchez** [comment]
Looking forward for this PR!

**Comment by fschwiet** [comment]
Released as version 2.0.1.  Thanks for your patience and help.

**Pull request merged**
